{{- if .Values.admin.users }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-y-admin-users
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: blue-y-premium
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.admin.users }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
